### ISSUE TITLE
ActionType ActionType.Enable in a Service Bus message disables the user account

### ISSUE THREAD

**Issue by mordoan** [protoface/AdServicePoC#2]
Hello,
first of all, thank you very much for your time and effort.

The app works great so far. We only encountered the following issue:

When we send a message via the Service Bus queue with `"ActionType": "ActionType.Enable"`, the worker receives the message, parses the user correctly but then disables to user.
We changed the default value in the line
```c#
public ActionType Action { get; set; } = ActionType.Disable;
```
to `ActionType.Enable`. The behaviour is then reversed. All messages enable the user independent of the `ActionType`.

Please let me know if you want me to debug or test something 😄

**Comment by protoface** [comment]
Hi,
thanks for bringing this to my attention.

I just pushed a commit which should fix the issue.
Instead of expecting the name of the action in a string, the json parser used the underlying enum´s integer-value.

If you encounter any other issues, feel free to contact me.

Thanks

**Comment by mordoan** [comment]
I was just now able to test your changes.

Sadly the `JsonConverter` fix seems to be not working on my end.

To confirm my suspicion, I added the line
```c#
logger.LogInformation("Action type was parsed as {action}", action.Action); 
```
above the `switch` statement which disables/enables the user.

This are the logs:
![Image](https://github.com/user-attachments/assets/401bb6ca-aa12-48c1-81e1-56a44ba49db7)

The first message is sent with `ActionType.Enable` and the user still gets disabled (which is the default in `AdIdentityActoins.cs`.

Please let me know, if I should debug something else

**Comment by protoface** [comment]
Sorry for only responding to you now.

The issue which you are experiencing right now is fully my fault for not catching it in your first message.
The "ActionType"-Property in your Json message includes the enum-type name `"ActionType": "ActionType.Disable"` instead of just the enum-value name `"ActionType":"Disable"`.

![Image](https://github.com/user-attachments/assets/3ca9ef57-c892-4145-ba3d-dfd39f8dbe09)

I am somewhat perplexed the json parser doesnt error-out when encountering a payload like this, but I also couldn't find a configuration flag for customizing this behaviour (besides writing my own enum converter).

**Comment by protoface** [comment]
I just pushed an commit, implementing a strict enum converter without the fallback behavior. Trying to parse an invalid value will now result in dead-lettering the message.

Please test these changes in your environment, whenever you're able to. 
Thanks

**Comment by mordoan** [comment]
Thanks for your continued effort 👍 

I tripple checked that I actually have you latest version pulled, build and running on the server.
Sadly the `ActionType` from the messages are still set to the default value independent of the message:

Default `ActionType.Disable`:

![Image](https://github.com/user-attachments/assets/c39d33ba-84a8-4b8c-8507-169c9e4f2241)

Default 'ActionType.Enable`:

![Image](https://github.com/user-attachments/assets/9f0cfc3e-863d-4c41-b632-3527f74c4897)

In both cases I send the following three messages: Enum value without quotes, Enum value with quotes, Enum Type.Value with Quotes (i.e. `Disable`, `"Disable"`, `"ActionType.Disable"`).

I'm not very versed in C#, but to me the parsing error for the value without quotes looks like that the default parser still in use and not your custom one. Could this be the case?

Also I'm able to debug stuff, if you need more information. I know programming and debugging, I just don't know C#

**Comment by protoface** [comment]
Your error descriptions are so detailed, there isn't much extra debugging needed. 

In this case, the property name in the json message ("ActionType") isn't the same as in the datamodel ("Action"). 

In my hurry, in my last message I accidentally wrote `"ActionType":"Enable"`, which won't work because the json parser can't associate "ActionType" with any property in the datamodel. The correct way is `"Action":"Enable"`.

![Image](https://github.com/user-attachments/assets/4bf563c1-a8d6-476d-90bd-d0aa30282974)

I just pushed another commit, implementing a safeguard against this exact case. 
Sorry for the inconvenience caused by my oversight.

**Comment by mordoan** [comment]
Ah, got it.

<img width="516" alt="Image" src="https://github.com/user-attachments/assets/175e68df-cc2e-4a09-b12c-05d0eff221bc" />

Works now, thank you so much 👌
